### ISSUE TITLE
Why set implicit defaults?

### ISSUE THREAD

**Issue by ThaNarie** [dwightjack/vue-types#10]
While I love this library, I wonder why there was chosen to set implicit defaults for a lot of types. 
This creates a difference between:
```
foo: String
foo: VueTypes.string
```
They are both optional, but one has a value of `undefined` where the other is `""`. Due to this it's not possible to check if someone passed an empty string or omitted the property.

When using this lib, I'd like to just use it everywhere to be consistent, but now I have to revert back to using the native option for optional properties that don't have a default set.

It also requires some extra changes when switching between required and optional property definitions.

There might be a valid reason for this that I'm overseeing, but otherwise I'd suggest to keep the default to `undefined` by default, and optionally add another modifier to execute the current behaviour.

**Comment by dwightjack** [comment]
Hi,
thank you for the feedback.

The idea behind vue-types was in fact to have a quick way to set a type with an _empty_ default, while keep using native options for everything else to keep is simple.

I agree that always using vue-types would make the code more consistent. 

I'll keep this in mind for the next major version of the library. 😃

**Comment by dwightjack** [comment]
Hi, I added an option to disable or customize implicit defaults ([docs](https://github.com/dwightjack/vue-types#native-types-configuration)) in version 1.0.0.

I'm closing this issue, If you find any problem please open another issue. Thanks for you feedback!
