### ISSUE TITLE
sensibleDefaults code is missing in the build versions of v1.0.0

### ISSUE THREAD

**Issue by hjeti** [dwightjack/vue-types#11]
The new sensibleDefaults code is missing in the dist and es folder of v1.0.0 when installed using npm. I can only find the sensibleDefaults code in the src folder.

**Comment by dwightjack** [comment]
Weird... It should be processed by the prepublish hook. Will check it later.

**Comment by dwightjack** [comment]
Ok, didn't understand what happened... 

Published a new version 1.0.1.

Let me know if it works

**Comment by hjeti** [comment]
v1.0.1 fixed the problem. Thanks.
