### ISSUE TITLE
.def() doesn't work

### ISSUE THREAD

**Issue by MatteoGabriele** [dwightjack/vue-types#12]
Hi, I'm having some troubles declaring default values in my shape

in this example i'm expecting the `theme` property to be `#E58005` if the object doesn't contain that property, instead my object contains only the properties I add.

```js
import type from 'vue-types'

export default type.shape({
  author: type.string.isRequired,
  text: type.string.isRequired,
  theme: type.string.def('#E58005')
})
```

if I receive this object as a prop of my component

```js
{
 author: 'matteogabriele',
 text: 'lorem ipsum'
}
```
I'm expecting this 

```js
{
 author: 'matteogabriele',
 text: 'lorem ipsum',
 theme: '#E58005'
}
```

thanks for your time, love this package! :)

**Comment by dwightjack** [comment]
Hi,

under the hood the `shape` type sets a prop validation object like:

```
{
    type: Object,
    validator() {
      // a custom validator that checks the prop value against the shape
    }
}
```

The only way to get a default shape is to use the `.shape().def()` method, but in that case the default shape will just be used when the prop is missing instead of beeing merged with the partial object.

Anyway this behavior matches the Vuejs docs. What's misleading is that the user can invoke `.def()` without any warning from the library (that's my fault) 😅 .
Looking at vue's source I believe there's no way to get the behavior you're expecting.

**Comment by MatteoGabriele** [comment]
yeah I see what you mean, that would be really powerful though: super useful. 

feel free to close the ticket if there's no way to achieve that or at least the warning would be nice :) 

speaking about warnings, maybe you prefer a separate ticket, but warning for type checks are not super straight forward in my opinion: what is missing for me is the actual key name. 

if i add a prop 'foo' with type string, the console will only complain about a number being passed instead of a string but doesn't  specify which key. it's very hard to debug. 

Thanks foe your time.

**Comment by dwightjack** [comment]
Yep, more meaningful warnings would be helpful. Opened #13 about it.

Digging in the source, relevant lines about prop validation are [here](https://github.com/vuejs/vue/blob/dev/src/core/util/props.js#L32). As far as I can see, default values are used just when prop value is `undefined`.

To achieve what you're looking for you could use both props and computed:

```js
{
  props: {
    item: VueTypes.shape({ ... })
  },
  computed: {
    mergedItem() {
      return Object.assign({
        theme: '#E58005'
      }, this.item)
    }
  }

}
```
