### ISSUE TITLE
More meaningful warning on `.shape` check

### ISSUE THREAD

**Issue by dwightjack** [dwightjack/vue-types#13]
>, but warning for type checks are not super straight forward in my opinion: what is missing for me is the actual key name.

> if i add a prop 'foo' with type string, the console will only complain about a number being passed instead of a string but doesn't specify which key. it's very hard to debug.

see https://github.com/dwightjack/vue-types/issues/12#issuecomment-305397761

**Comment by arnthor3** [comment]
Any news on this issue? This would be really useful to have.

**Comment by martinmckenna** [comment]
+1. The current logging is completely useless and is making me spend more than a few minutes trying to track down what key I'm missing

**Comment by dwightjack** [comment]
@martinmckenna @arnthor3 I've published the `1.8.1-beta.1` version with some possible improvements to the `oneofType` and `shape` logging.

I would greatly appreciate your feedback on this. 😃

**Comment by dwightjack** [comment]
I just released v2.0.0 which comes with more descriptive errors: https://github.com/dwightjack/vue-types/releases/tag/2.0.0

I'm closing this for now. Feel free to open a new issue if you have other issues with logging.
