### ISSUE TITLE
Is it full 1 to 1 clone of react's prop-types? 

### ISSUE THREAD

**Issue by nickmessing** [dwightjack/vue-types#15]
Hello,

We are a small team that started a tiny react2vue converter called [vueact](https://github.com/vueact), I was thinking of using `vue-types` as a replica of `prop-types`, is it 1-to-1 clone?

**Comment by dwightjack** [comment]
Hi nice project!

Looking at the react prop-types library I spotted the following missing validators:

* `PropTypes.symbol`
* `PropTypes.node` (I believe this could be replaced by `VueTypes.any` in Vue.js)
* `PropTypes.element`

They don't look so difficult to implement, I could add them in the next release.

It's also missing the ability to pass a function as argument to `PropTypes.arrayOf`, while custom validators are available through the undocumented [`VueTypes.custom`](https://github.com/dwightjack/vue-types/blob/master/src/index.js#L57) method.

**Comment by dwightjack** [comment]
Ah, one major difference it that VueTypes provide sensible defaults for props. 

In order to match React behaviour you can disable those defaults by setting [`sensibleDefaults`] (https://github.com/dwightjack/vue-types#native-types-configuration) to `false`

**Comment by dwightjack** [comment]
Hi I've further investigated this issue. Here are some updates:

* with release [1.1.1](https://github.com/dwightjack/vue-types/releases/tag/1.1.1) I've added `Vuetypes.symbol` check
* I cannot find a way to add `VueTypes,element` check. For my understandings, this type of check should be against Vue's VNode object which is not exposed by Vue.
* `arrayOf` function signature and `node` can be converted the way I posted in my previous post. This way we can keep the codebase slimmer.

Closing for now. If you need more details or other features feel free to reopen it.

**Comment by nooooooom** [comment]
@dwightjack hi, Any good ideas about `VueTypes.element` now? 

In my opinion, it just needs to satisfy the `h` function, it looks like,
 ```typescript
{
  type: [String, Object, Function] as PropType<Parameters<typeof h>[0]>
}
```

**Comment by dwightjack** [comment]
@nooooooom In my experience a node prop is rarely used so I am not sure it's a good idea to add it to the library. Anyway, you can add your own validators using one of the [extension methods](https://dwightjack.github.io/vue-types/advanced/extending-vue-types.html). It might be something like:

```ts
import { toType } from 'vue-types';

const element = () =>
  toType('element', {
    type: [String, Object, Function]  as PropType<Parameters<typeof h>[0]>,
  })
```

**Comment by nooooooom** [comment]
> @nooooooom根据我的经验，很少使用节点道具，因此我不确定将其添加到库中是否是个好主意。[无论如何，您可以使用其中一种扩展方法](https://dwightjack.github.io/vue-types/advanced/extending-vue-types.html)添加自己的验证器。它可能是这样的：
> 
> ```ts
> import { toType } from 'vue-types';
> 
> const element = () =>
>   toType('element', {
>     type: [String, Object, Function]  as PropType<Parameters<typeof h>[0]>,
>   })
> ```

Thanks, it worked for me.

Using element as props in Vue is probably not a common practice.
