### ISSUE TITLE
.isNullable

### ISSUE THREAD

**Issue by lmiller1990** [dwightjack/vue-types#16]
Hi!

First up awesome project, big game changer for my team. 

One feature I'd like to see is a `.isNullable` for types. For example, I have component called `SubTab` that can have a prop array of more `SubTabs` that can be null. So I'd like to be able to do something like:

``` js
 export default {
    props: {
      subtab: VueTypes.shape({
        /* ... */
        SubTabs: VueTypes.array.isNullable,
      })
    },
  }
 ```

What do you think? I can look into this within the next week if so.

If there is already something in the API that will allow this behavior, please let me know too.

**Comment by dwightjack** [comment]
Hi thanks!

that looks doable. Translated to Vue's type validation a nullable type could be configured as an array of types:

```
    nullableArrayProp: {
        type: [Array, null]
    }
```

Anyway looking at the [typed sourcecode](https://github.com/vuejs/vue/blob/dev/src/core/util/props.js#L14) it seems that array types accepts just functions/constructors, not `null`. Example [here](https://jsbin.com/jomayor/4/edit?html,js,console,output).

The only way to go should be a custom `validator` function maybe using the internal `validateType` function which, at the moment, doesn't check against `null` types [see here](https://github.com/dwightjack/vue-types/blob/master/src/utils.js#L143)

If you have time to send a PR, it'd be great. Feel free to ask for more details. :)

**Comment by lmiller1990** [comment]
Hey,

Thanks for the pointers on how to go about this. I'll have a shot at it on the weekend!

**Comment by lmiller1990** [comment]
Had a look, will keep at it this week. A little more tricky that expected but should be doable.

**Comment by dwightjack** [comment]
Hi, cool!
This week I'm away from home but should be available if you need some hints. 
Anyway next week I'll be back at work and I could try something myself as well :-)

**Comment by lmiller1990** [comment]
Hey. Sorry for going quiet all of a sudden. I notice you assigned this to yourself -- I'm giving it a shot right now, I'm interested in learning more about how Vue checks props either way, if you've made some progress I'd love to see that too! If I get anything done in the next few hours I'll throw you a link to the branch as well.

**Comment by lmiller1990** [comment]
Some progress:

Seems reasonably doable, however I'd like to clarify my approach.

Firstly, if we have something like

```props: {
  someBool: VueTypes.bool.isNullable
}
```

This would have to add an implicit `isRequired` as well? If I mark a prop is `isNullable`, what I expect is that is _can_ be null, or else it should fit the other requirements set. Regarding the above example:

` someBool: VueTypes.bool.isNullable`

would mean:

`someBool = true //=> valid`
`someBool = false //=> valid`
`someBool = null // => valid`
`someBool = '5'` // => invalid`

So `.isNullable` is more like `.isRequiredOrCanBeNull`.

Have you had any thoughts about this issue?

**Comment by dwightjack** [comment]
Hi,

no problem. I assigned the issue to myself just to keep track of it on my todolists, but I didn't have time to work on it.

I get your point. Making the prop required makes sense, because in Vue prop check when a prop is undefined or null and not required it just skips the whole process. Making it required will trigger the validation. 

As for the implementation, I think the best solution would be, in the `withNullable` getter to set (or patch it if already defined) the prop's custom `validator` function checking for null value ( `if (value === null) return true`) and set its required flag to `true`.

**Comment by lmiller1990** [comment]
Thanks for the pointer. I want to get this done this week! Will keep you updated.

**Comment by dwightjack** [comment]
Cool! Feel free to ping me for any issue or hint.

**Comment by lmiller1990** [comment]
Hey, sorry about the long silence. Fairly busy lately, not sure if/when I'll get around to this. Sorry. If you do end up implementing it, please let me know :)

**Comment by dwightjack** [comment]
No problem, will keep the issue open for further updates :)

**Comment by dwightjack** [comment]
Hi

sorry for the delay. Lately I've been busy on other projects. 

I've done a first implementation of the `.isNullable` modifier [on this branch](https://github.com/dwightjack/vue-types/tree/feature/isnullable). Relevant code is [here](https://github.com/dwightjack/vue-types/blob/feature/isnullable/src/utils.js#L131).

In the `examples` folder you should find a working test as well.

Let me know if it feels good to you.

On an unrelated subject, I noticed from your github profile that you live in Tokyo; I'll move there starting from late Jan 2018. Nice to see so many Vue developers in Japan!

**Comment by decademoon** [comment]
Just a thought, perhaps we could add `isOptional` too which checks `== null` (unlike `isNullable` which checks `=== null`).

**Comment by lmiller1990** [comment]
@dwightjack woah, cool. We should meet up for sure if you are in town! Are you working in tech here? Vue is very popular; much more so than React and Angular. If you speak decent Japanese, you can definitely land a job. 

I host a biweekly (Vue study event)[https://vuejs-moku.connpass.com/], let me know if you wanna come along.

**Comment by decademoon** [comment]
This might also be of interest: https://github.com/vuejs/vue/issues/7720

Basically, there is no way to enforce a prop to be non-null at all times without specifying `required: true`, but doing so has the implication that the prop cannot be omitted from the template, even if that prop has a default value.

**Comment by dwightjack** [comment]
@decademoon Thanks for the insight. I believe the point of @lmiller1990 was to allow `null` as explicit value. I believe that `isOptional` flag is essentially achieved by marking the prop as `required: false`, but maybe I'm missing your use case.

Thanks for referencing the issue in Vue.js repo, it clarifies some points in Vue.js prop validation that are sometimes difficult to grasp just from the docs.

**Comment by dwightjack** [comment]
@lmiller1990 Yep working at a web agency around Aoyama. My Japanese is raw so it'n not always that simple, but 頑張っている! 😝 

The event you're hosting looks cool! Will check it out for sure! (PS: joined your slack team, よろしく！)

**Comment by ChambreNoire** [comment]
Hi,
Looks good! Any idea when this will make it into the master (or if anyone knows of a temporary workaround)?
Cheers

**Comment by dwightjack** [comment]
@ChambreNoire it's basically done but I froze the issue because it's unclear which use cases it should cover. We could discuss that here and try to get it done (or drop it). @lmiller1990 @decademoon 

In the meanwhile I was thinking that maybe a solution could be use a `OneOfType` validation:
```js
{
  prop: VueTypes.oneOfType([
    VueTypes.string,
    { validator: (value) => value === null }
  ]).isRequired
}
```

Didn't test it but it should be fine for simple use cases.

**Comment by lmiller1990** [comment]
I think we need to think of the actual use cases a little. @ChambreNoire what is your use case? After doing more Vue and working on larger systems, I found that often having a `nullable` prop worked out worse in the long run. I think this is why Vue now enforces props to be either `required` or have a  `default` value.

However I believe there are still some valid use cases - can you explain yours? I think I ended up going with an empty array as the default in my case.

**Comment by dwightjack** [comment]
After some thinking I believe @lmiller1990 point is right. 

Let's close this issue for now. I'm not going to I'm not going to delete the feature branch, so if a specific use case arises, we could address it starting from the code we've already developed.

**Comment by maxpou** [comment]
if someone Google this problem and ends here, here's a solution:

```js
props: {
  myHandler: VueTypes.func,
},

// ...

if (myHandler.name === 'noop') {
  // props empty!
}

**Comment by martinmckenna** [comment]
I would love this PR tbh. My use case is that I'm using a 3rd party API and when I make a network request, there are some Object keys that may not exist at all.

So to defend against that, I made all the non-existent  keys default to `null` to appease the type checker, but now I'm realizing there isn't any `isNullable` functionality in this lib.

This imo is a no-brainer. Other libs like Yup do this so well:

https://github.com/jquense/yup#mixednullableisnullable-boolean--true-schema

**Comment by lmiller1990** [comment]
@martinmckenna in that case can you just define it without `default` or `required` (that would be undefined, which is basically the same as null for missing key).

**Comment by dwightjack** [comment]
@martinmckenna I agree with @lmiller1990: it is usually better to make a key `undefined` instead of setting it to `null` in order to communicate that it's optional.

If I'm understanding it correctly your issue involves a type checker as well (TypeScript maybe?). In that case, you might want to use the [`Partial` helper](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialt) to make all keys of the type optional.

**Comment by martinmckenna** [comment]
But it's not an optional prop, and I want other people on my team to understand that

`null` means you did pass the prop, but it just has no value

`undefined` means you didn't pass the prop at all. I want my team members to get console warnings here.

**Comment by dwightjack** [comment]
I think this issue can be closed. Feel free to re-open if there's something new on the subject
