### ISSUE TITLE
PropTypes.boolean has some problem

### ISSUE THREAD

**Issue by cloudyan** [dwightjack/vue-types#17]
```
import PropTypes from 'vue-types'
...
props: {
  block: PropTypes.boolean,
}


// usage
<Button block>Block</Button>


this.$props.block === "" // true

this should be  === true, not ""
```

**Comment by dwightjack** [comment]
Hi,

ATM I cannot verify that but I see you're setting the prop without `:` (ie: `<Button :block>`). Vue treats props'value set without `:` as string literals.

**Comment by dwightjack** [comment]
Confirmed. Without the `:` the prop is [cast to string](https://vuejs.org/v2/guide/components.html#Literal-vs-Dynamic). 

Moreover it should be better to provide an explicit value for the prop, even if it's a boolean:

```
<Button :block="true">Block</Button>
```
