### ISSUE TITLE
eslint vue/require-default-prop warning

### ISSUE THREAD

**Issue by alexmccabe** [dwightjack/vue-types#179]
I've set up my component as outlines in your documentation, but i am still getting the eslint warning when using the `isRequired` prop.

![CleanShot 2021-09-08 at 10 52 02](https://user-images.githubusercontent.com/2529110/132488098-32e4c6df-f895-4f86-8caa-d286ff312d95.png)
![PixelSnap 2021-09-08 at 10 54 32](https://user-images.githubusercontent.com/2529110/132488384-e5198297-9271-4375-9403-f5dde96ea49f.png)

```js
import { string } from 'vue-types';

export default {
  props: {
    name: string().isRequired,
  }
}
```

`eslint-plugin-vue` is at it's current latest version (6.2.1) at the time of writing. Am I missing something?

**Comment by dwightjack** [comment]
Hi, could you share your ESLint configuration?

**Comment by alexmccabe** [comment]
Hi Dwight, here's the `.eslintrc.js`. I added the vue-types eslint plugin and it resolved the issue, however your package there says it's no longer needed.

```
module.exports = {
    env: {
        browser: true,
        es6: true,
        amd: true,
    },
    ignorePatterns: ['spark-components'],
    extends: [
        'eslint:recommended',
        'plugin:vue/strongly-recommended',
        // 'plugin:vue-types/recommended', // uncommenting this line fixes the warning
        'plugin:prettier/recommended',
        'prettier',
        'prettier/vue',
    ],
    parserOptions: {
        parser: '@babel/eslint-parser',
        sourceType: 'module',
        ecmaVersion: 2020,
    },
    plugins: ['prettier'],
    rules: {
        'prettier/prettier': 'error',
        'no-unused-vars': 'warn',
        'no-multi-assign': 'error',
        'no-useless-escape': 'off',
        'one-var': ['error', 'never'],
        'padding-line-between-statements': [
            'error',
            { blankLine: 'always', prev: 'block-like', next: '*' },
            { blankLine: 'always', prev: '*', next: 'return' },
            { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
            { blankLine: 'always', prev: '*', next: ['const', 'let', 'var'] },
            {
                blankLine: 'any',
                prev: ['const', 'let', 'var'],
                next: ['const', 'let', 'var'],
            },
            { blankLine: 'never', prev: 'return', next: '*' },
        ],
        quotes: ['error', 'single', { avoidEscape: true, allowTemplateLiterals: false }],
        'no-var': ['error'],
        'no-console': ['error', { allow: ['error'] }],
        'vue/attributes-order': [
            'error',
            {
                order: [
                    'DEFINITION',
                    'GLOBAL',
                    ['UNIQUE', 'SLOT', 'OTHER_ATTR'],
                    'EVENTS',
                    'LIST_RENDERING',
                    'CONDITIONALS',
                    'TWO_WAY_BINDING',
                    'RENDER_MODIFIERS',
                    'OTHER_DIRECTIVES',
                    'CONTENT',
                ],
                alphabetical: true,
            },
        ],
        'vue/component-name-in-template-casing': [
            'error',
            'PascalCase',
            {
                registeredComponentsOnly: false,
                ignores: [],
            },
        ],
        'vue/html-indent': ['error', 4],
        'vue/html-self-closing': [
            'error',
            {
                html: {
                    void: 'any',
                },
            },
        ],
        'vue/no-static-inline-styles': [
            'error',
            {
                allowBinding: false,
            },
        ],
    },
    globals: {
        $: true,
        Bus: true,
        Echo: true,
        moment: true,
        module: true,
        process: true,
        swal: true,
        Vue: true,
        __dirname: true,
        describe: true,
        test: true,
        jest: true,
        expect: true,
        global: true,
        it: true,
        _: true,
        __: true,
    },
};
```

**Comment by dwightjack** [comment]
Hi, the latest changes in `eslint-plugin-vue` made me hope I didn't have to deal with ESLint anymore but I was wrong 😅. 

It looks like patterns like `string()` are ignored but not `string().isRequired`.

I will think of a fix for it.

**Comment by alexmccabe** [comment]
Haha sorry @dwightjack. I wish I could help, but I've not spent any time with the eslint plugin ecosystem 😔

**Comment by dwightjack** [comment]
Hi, so I did some tests and it looks like the error is generated when using `eslint-plugin-vue^6` but not `eslint-plugin-vue^7`, so that might be the reason for my misunderstanding.

Anyway, I have published a new version of the plugin (`eslint-plugin-vue-types@2.1.0-rc.1`) that should cover some more cases and without deprecation warning. Of course you need to uncomment `'plugin:vue-types/recommended'` as well in your config.

If this setup is working for you, I will update the library documentation.

**Comment by alexmccabe** [comment]
Ahh neat! I can try updating to `eslint-plugin-vue^7`, but that may not work and may break a lot of stuff, I know our build is fairly fragile if we start upgrading random bits, but linting _should_ be fine.

Thanks for spending time digging into this!

**Comment by dwightjack** [comment]
Hi, I've published the stable version of `eslint-plugin-vue-types@2.1.0` and added a page about this issue on the documentation (https://dwightjack.github.io/vue-types/guide/troubleshooting.html).

I am going to close this issue for now, but feel free to re-open it if you find any other problem.

**Comment by alexmccabe** [comment]
Nice! good work bud, thanks for doing that! Will be upgrading this week
