### ISSUE TITLE
Best way to share custom prop types definition ?

### ISSUE THREAD

**Issue by nddery** [dwightjack/vue-types#18]
We've been trying to share custom prop type definitions between components with some success. However, when adding `isRequired` to a shared type on a component, it get's applied to all other component using that shared type afterwards, even if they don't specify `isRequired`.

See https://codepan.net/gist/fc23c60fc04574653ad45a1c4aac5f9e

How would you recommend sharing custom prop types between component ?

**Comment by dwightjack** [comment]
Hi,

to lower complexity and side effects when using flags, starting from [v1.0.0](https://github.com/dwightjack/vue-types/releases/tag/1.0.0) type objects aren't cloned but extended when using flags.

An option for your scenery would be to leverage the same logic behind builtin types: object getters. This way you could define your own type definitions in one module and use them onto your components.

I've updated your example here: https://codepan.net/gist/88e584bc16bd889db3ec86ee8e0944d8

Let me know if it works.

**Comment by nddery** [comment]
That works beautifully! Thanks!
