### ISSUE TITLE
VueTypes.arrayOf() throws and error

### ISSUE THREAD

**Issue by Ble3k** [dwightjack/vue-types#20]
https://pastebin.com/8XSL2gU7

Hi, this code throws an error (https://ibb.co/gP9vXb), could somebody explain why ?

**Comment by dwightjack** [comment]
Hi,

vue-types types return a complete Vue prop validation object. So instead of:

```js
arrayProp: {
  type: VueTypes.arrayOf(String).def([]),
}
```

you should write:

```js
arrayProp: VueTypes.arrayOf(String).def([])
```

**Comment by Ble3k** [comment]
Thanks, my fault, should read docs better))

**Comment by dwightjack** [comment]
No problem :)
