### ISSUE TITLE
Question:Use defineProps has ESLint Error

### ISSUE THREAD

**Issue by menghany** [dwightjack/vue-types#202]
Hi,I use vue-types in defineProps.
that eslint has error
`defineProps` are referencing locally declared variables.(vue/valid-define-props
![eslint error](https://user-images.githubusercontent.com/13767186/141707972-0482a93a-c1be-430e-a691-7c8691f4aada.png)
)

**Comment by dwightjack** [comment]
Hi,
if you're using the `<script setup>` syntax you need to import the validator in a normal `<script>` block. You can then use it inside the setup block.

This should work:

```html
<script>
import { string } from 'vue-types'
</script>

<script setup>
const props = defineProps({
  stcd: string()
})
</script>
``` 

Reference: https://eslint.vuejs.org/rules/valid-define-props.html#rule-details

**Comment by menghany** [comment]
> Hi, if you're using the `<script setup>` syntax you need to import the validator in a normal `<script>` block. You can then use it inside the setup block.
> 
> This should work:
> 
> ```
> <script>
> import { string } from 'vue-types'
> </script>
> 
> <script setup>
> const props = defineProps({
>   stcd: string()
> })
> </script>
> ```
> 
> Reference: https://eslint.vuejs.org/rules/valid-define-props.html#rule-details

Thanks, this solved my issue
