### ISSUE TITLE
validateType throw an error when used with shape

### ISSUE THREAD

**Issue by J3m5** [dwightjack/vue-types#226]
Hello and thank you for this nice lib!

When trying to use validateType with a shape it throw an error

```js
validateType(shape({ a: 1 }), { a: 1 })
``` 

throw error:
`TypeError: Right-hand side of 'instanceof' is not an object`

Is this normal and there is another way of using validateType for shapes?

**Comment by dwightjack** [comment]
Hi, 

I think that the shape definition is not correct. It should be:

```ts
validateType(shape({ a: Number }), { a: 1 })
``` 

If you explicitly need `a` to be `1`, you might want to use the `number` validator:

```ts
validateType(shape({ a: number().validate((n) => n === 1) }), { a: 1 })
```

**Comment by J3m5** [comment]
Oh, my bad, I see now, thank you!
