### ISSUE TITLE
Set the def attribute, the props received by the component are still the default type

### ISSUE THREAD

**Issue by bosens-China** [dwightjack/vue-types#284]
``` js
export const switchProps = () => {
  return {
    modelValue: bool().def(undefined),
    disabled: bool(),
  };
};

```

``` js
import { defineComponent, ref } from 'vue';
import { switchProps } from './switchTypes';

export default defineComponent({
  props: switchProps(),
  setup(props, { emit, attrs }) {
    console.log(props);

    
  },
});

```
output

![image](https://user-images.githubusercontent.com/39508895/181685263-5ea7f8fa-8177-4a54-9a67-9eefbfcf2fa4.png)

expect
``` js
{modelValue: undefined, disabled: false}
```

**Comment by dwightjack** [comment]
@bosens-China I think this behavior is related to Vue [boolean casting](https://vuejs.org/guide/components/props.html#boolean-casting). 

In your case, the `undefined` default value is cast to `false`.

**Comment by bosens-China** [comment]
But when I show it in the following way, it's OK

``` js
 modelValue: {
  type: Boolean,
  default: undefined
}

```

to

``` js
{modelValue: undefined, disabled: false}
```

**Comment by dwightjack** [comment]
I see. In Vue, boolean props and _nullable_ are always a gray area. At the moment `.def(undefined)` deletes the default property if present, so, changing this behavior might be a breaking change for other users.  

You can, anyway, create a custom validator to fit your case:

```ts
import { bool, fromType } from 'vue-types';

const boolWithUndefined = () =>
  fromType('boolWithUndefined', bool, {
    default: undefined,
  });

export const switchProps = () => {
  return {
    modelValue: boolWithUndefined(),
    // ...
  };
};
```

**Comment by bosens-China** [comment]
😭
Is it possible to force the behavior of `def`
I have explicitly specified "undefined" above

**Comment by dwightjack** [comment]
I took another look at the [source code](https://github.com/vuejs/vue/blob/1d8b892fcd9edcef1feeed74ad586beabb9f6df2/src/core/util/props.ts#L34). It is probably an edge case related to the boolean type, so I think I could allow explicitly setting the default to `undefined` only for `bool()` 🤔.

**Comment by dwightjack** [comment]
After further investigation, I think this is a breaking change. I will keep the issue open and see if other users think this feature is useful (cc @victorgarciaesgi). 

For the moment, the suggestion is to use a custom validator.

**Comment by bosens-China** [comment]
https://github.com/dwightjack/vue-types/issues/71

Found the same problem, I think it is still necessary, whether it is possible to determine the behavior of `def` by registering the global configuration

```  js
import { config } from 'vue-types'
config.mandatory = true;
```

**Comment by dwightjack** [comment]
Hi, I plan to release this change with version 5. At the moment I published it as a beta version: `vue-types@5.0.0-beta.1`.

let me know if it works as expected.

**Comment by bosens-China** [comment]
test later,But can other types be forced to specify `undefined ` this is in line with the official documentation
``` js
export const switchProps = () => {
  return {
    one: number().def(undefined),
    two: bool().def(undefined),
    three: string().def(undefined),
    // ... other
  };
};
```

**Comment by dwightjack** [comment]
If I understand correctly, boolean prop types are the only one where the value is casted if a default property is not defined. In all other cases, if the prop does not have a default property, the prop value is anyway `undefined` (https://github.com/vuejs/vue/blob/00458cd38d209410d3c675729230a42a0a34a4b9/src/core/util/props.ts#L70).

I think that the validators (used as named imports) does not force any sensible default, so assigned props should have a `undefined` value when nothing is passed. 

Maybe I don't understand your use case. Could you provide an example with a couple of components?

**Comment by bosens-China** [comment]
You're right

**Comment by bosens-China** [comment]
``` vue
<script >
import { defineComponent } from "vue";
import { number, string, object, array, func, bool } from "vue-types";

export default defineComponent({
  props: {
    test1: number().def(undefined),
    test2: string().def(undefined),
    test3: object().def(undefined),
    test4: array().def(undefined),
    test5: func().def(undefined),
    test6: bool().def(undefined),
  },
  setup(props) {
    console.log(props);
    return () => 123;
  },
});
</script>

```

-----------------
``` js
test1: undefined
test2: undefined
test3: undefined
test4: undefined
test5: undefined
test6: undefined
```
