### ISSUE TITLE
Wrong documentation for number prop default

### ISSUE THREAD

**Issue by tiku91** [dwightjack/vue-types#289]
**Describe the bug**
Wrong documentation for number prop default

**To Reproduce**
1. Go to https://dwightjack.github.io/vue-types/guide/validators.html#native-validators
2. The section says: 
```
const numProp = number()
// numProp === { type: Number, default : 0}
```

**Expected behavior**
According to the tests, this should be 
`// numProp === { type: Number }`
or
`// numProp === { type: Number, default: undefined}`

**Library version**
4.2.1

**Comment by dwightjack** [comment]
Fixed in https://github.com/dwightjack/vue-types/commit/86412ea294b99457fbb7dee132283f973456111a and published (might need to clean the cache to see it).
