### ISSUE TITLE
Vue Eslint error

### ISSUE THREAD

**Issue by gianko** [dwightjack/vue-types#29]
code:
```
  props: {
    color: VueTypes.string.def('black'),
  },
```

lint error:
`Prop 'color' requires default value to be set  vue/require-default-prop`

**Comment by dwightjack** [comment]
Hi,

Thanks for the issue. I've never properly tested vue-props with latest vue-eslint-plugin.

Will check it out.

**Comment by dwightjack** [comment]
@gianko I've opened an issue on the vue-eslint-plugin repository because I'm not sure how to proceed to solve this issue.

In the meawhile the only solution I see is to disable `vue/require-default-prop` rule, even if I know it sucks... 😢

**Comment by Xotic750** [comment]
This is really unfortunate, this is a blocker for introducing this project to other projects that I am involved in. If I have any ideas I will be sure to contribute.

**Comment by dwightjack** [comment]
Thank you!

**Comment by dwightjack** [comment]
@gianko I've just released an ESLint plugin to make vue-types play alongside `eslint-plugin-vue`: https://github.com/dwightjack/eslint-plugin-vue-types

After installing it, you should just add `'plugin:vue-types/strongly-recommended'` as the last `extends` preset in your configuration

Let me know if it works for you.

**Comment by dwightjack** [comment]
Closing this for housekeeping. Feel free to re-open it if something new happens.
