### ISSUE TITLE
Explore TS typings

### ISSUE THREAD

**Issue by dwightjack** [dwightjack/vue-types#31]

**Comment by Vincent1993** [comment]
Probably when will finish this?

**Comment by dwightjack** [comment]
I'm still exploring it, since I'm pretty new to typescript (had previous experience with flow, though).

I'm not sure whether the best option is to rewrite the library or provide just a row definition file.

Suggestions?

**Comment by evenfrost** [comment]
Either will do in my opinion. Rewriting the library with TypeScript from scratch is an awesome idea if you want a deeper dive into TS. But it'll definitely take more time than just adding a `d.ts` file to the project, which is totally acceptable option as well.

**Comment by dwightjack** [comment]
Actually I've already done some work. It  can be found on this branch: https://github.com/dwightjack/vue-types/tree/feature/typescript

Still lacking tests and maybe some review. If anyone more skilled with TS than me could review it, feedbacks are welcome :)

**Comment by dwightjack** [comment]
Hi, sorry for the delay. 

I had some problems trying to port the build setup and tests suite to TypeScript (karma + rollup + ts has been the main blocker). 

In the end I had to revert to JS + separate [TS typings](https://github.com/dwightjack/vue-types/tree/master/types). 

Released under [v1.3.0](https://github.com/dwightjack/vue-types/releases/tag/1.3.0)

Since that's my first attempt to TypeScript, feedback are welcome 😄

**Comment by dwightjack** [comment]
Published a small bugfix as v.1.3.1

I'm closing this issue. If you have any bug report or improvement feedback feel free to open another issue.
