### ISSUE TITLE
`validateType(String, undefined) === true`?

### ISSUE THREAD

**Issue by KnifeFed** [dwightjack/vue-types#325]
**Describe the bug**

`validateType(String, undefined)` returns `true`.
So does `VueTypes.utils.validate(undefined, VueTypes.string)`.
Actually, it returns true for any validator if the value is undefined.
That can't be right, or am I missing something?

**Library version**
5.0.2

**Vue.js version**
2.7.13

**Comment by dwightjack** [comment]
Hi,

The `validateType` mostly follows Vue's prop validation logic. This means passed in that props (either in object format or constructors - like `String`) that are not required are always valid when their value is `undefined`.  
Using the `isRequired` flag should cause the validation to fail.

**Comment by KnifeFed** [comment]
How do you use the `isRequired` flag with `validateType` when type checking arbitrary values that aren't props?

**Comment by dwightjack** [comment]
Hi,

to better understand your use case, could you please share a sample code?

**Comment by KnifeFed** [comment]
I've been using it in all kinds of scenarios just for type-checking arbitrary values due to its convenience of checking and logging all in one (this is in a Vue 2 project without TypeScript). I just had not noticed yet that it gladly validates `undefined` as `true` no matter what type you're comparing against. Here's a sample that's as simple as it can get:

```js
function foo(bar) {
  console.log('bar', bar)
  const baz = validateType(String, bar)
  console.log('baz', baz)
}

foo('bar')
// bar bar
// baz true

foo(1)
// bar 1
// [VueTypes warn]: value "1" should be of type "String"
// baz false

foo()
// bar undefined
// baz true
```

In the last function call, I would expect `baz` to be `false` and to receive a warning since `undefined` is not a string.

**Comment by dwightjack** [comment]
I see. The function is meant to validate Vue prop definitions following the Vue's props logic. Sorry if that's not clear in the documentation. I am going to update it soon.

If you need to validate a value _in general_,  I would suggest to use something like [zod](https://zod.dev/).

**Comment by KnifeFed** [comment]
Oh, I see. Yeah, that was not clear to me as it says "Checks a value against a type definition" and props aren't used in the code examples, only static values like `validateType(String, 10, false)`. Then I don't really understand what the point of it is, since if invalid props are passed to a component, they would already get caught by using vue-types in `props`/`defineProps`..? Oh well, looks like I have some refactoring to do 🙂
