### ISSUE TITLE
Lodash isPlainObject vulnerability

### ISSUE THREAD

**Issue by ineghi** [dwightjack/vue-types#33]
Hi, 

A severe vulnerability has been listed for lodash before 4.17.5 version;
https://ossindex.sonatype.org/vuln/12e63c9c-b3f9-42d3-8541-dca1b72cad69

Are you already aware of this ?

**Comment by dwightjack** [comment]
@ineghi wasn't aware of it. Thanks for letting me know!

**Comment by dwightjack** [comment]
Since it looks like `lodash.isplainobject` is no more updated, I modified the codebase to use `lodash/isPlainObject` directly. The filesize of the compiled package is mostly unchanged.

Published as v1.3.3 

Thanks for your contribution!
