### ISSUE TITLE
Getting required: true, even if not added the isRequired flag

### ISSUE THREAD

**Issue by bietkul** [dwightjack/vue-types#37]
Hi, thanks for this library.
I'm getting some issues, when using types without any flag.
So, basically when I'm just defining a type like that
```js
value: types.number
```
By default, I'm getting `required` as `true` which is not expected.

**Comment by dwightjack** [comment]
Hi,

I've created a simple fiddle to reproduce the erro but it looks like it's working properly: https://jsfiddle.net/uv1573zp/4/

Could you share some more insight so that I could reproduce the error?

**Comment by bietkul** [comment]
Actually destructuring was the cause here too.
