### ISSUE TITLE
Uncaught TypeError: Cannot read property 'custom' of undefined

### ISSUE THREAD

**Issue by bietkul** [dwightjack/vue-types#38]
I'm getting this error when defining a type using `oneOfType` api.

Error:
https://i.imgur.com/qcx6LzL.png

Code:
```js
fields: oneOfType([String, arrayOf(String)])
```

**Comment by dwightjack** [comment]
Hi,

Looking at the code snippet I think you are importing individual methods from the library, something like:

```js
import { arrayOf , oneOfType } from 'vue-types'
```

VueTypes exports an object and some methods has internal reference to `this`. By destructuring it those methods lost their context.

I know importing just the needed types is convenient and concise, but right now that's not possible with VueTypes.

**Comment by bietkul** [comment]
Thanks, working well

**Comment by dwightjack** [comment]
Great!
