### ISSUE TITLE
validateType does not treat `null` the same as Vue does

### ISSUE THREAD

**Issue by jason-wolfe** [dwightjack/vue-types#383]
**Describe the bug**

`validateType({type: t}, null)` returns false, indicating that it does not pass prop validation. 

**To Reproduce**
1. Invoke `validateType({type: Object}, null)`
2. It will return false instead of true 

**Expected behavior**

`validateType({type: t}, null)` should return true for all type constructors, in order to match Vue's prop type validation. This is specified in the documentation for both [Vue 2](https://v2.vuejs.org/v2/guide/components-props.html#Prop-Validation) ("`null` and `undefined` values will pass any type validation") and [Vue 3](https://vuejs.org/guide/components/props.html#prop-validation) ("(`null` and `undefined` values will allow any type)").

It is of course good to reject these for `{type: t, required: true}`.

**Library version**
5.0.2

**Vue.js version**
Not involved in this code path.

**Comment by dwightjack** [comment]
Thanks! Fixed in `vue-types@5.0.3`.

**Comment by jason-wolfe** [comment]
Fantastic, thanks a ton @dwightjack !
