### ISSUE TITLE
validate can't determine param type

### ISSUE THREAD

**Issue by Ttou** [dwightjack/vue-types#405]
**Describe the bug**

![iShot_2023-06-21_10 12 21](https://github.com/dwightjack/vue-types/assets/4298437/3ac963a8-21af-4e8b-a091-dea9b922b533)

**Library version**

5.0.4

**Vue.js version**

2.7.14

**Comment by dwightjack** [comment]
@Ttou it should be fixed with [v5.1.0](https://github.com/dwightjack/vue-types/blob/main/packages/core/CHANGELOG.md#510). Let me know if it works.

**Comment by Ttou** [comment]
@dwightjack it works
