### ISSUE TITLE
Use a shim in production build

### ISSUE THREAD

**Issue by dwightjack** [dwightjack/vue-types#41]
In production props don't get validated. We could shave some filesize by using a *noop* shim in production build.

**Comment by atilacamurca** [comment]
there's a great example of a possible way to do this at <https://github.com/znck/prop-types/blob/master/src/index.js#L5>

**Comment by dwightjack** [comment]
@atilacamurca relevant commit is 9c9972f255387b089e2d3beeedb065441f08a511

**Comment by atilacamurca** [comment]
Can you provide the difference between the development and production on the README?

If you don't want to update every time the file size difference, you could put in percentage so people could see the real benefit to use the shim version in production.

**Comment by dwightjack** [comment]
That's right. Thank you fir the hint :)

**Comment by dwightjack** [comment]
@atilacamurca I added the details here: https://github.com/dwightjack/vue-types/tree/develop#production-build. Good call on the usage of percentages 👍

**Comment by dwightjack** [comment]
Published as of [v.1.5.0](https://github.com/dwightjack/vue-types/releases/tag/1.5.0). Closing for now. 
Feedbacks are welcome 😃
