### ISSUE TITLE
IDE claims "Instance member not accessible"

### ISSUE THREAD

**Issue by joakimbugge** [dwightjack/vue-types#43]
WebStorm 2018.3 claims the method `oneOf` is not accessible:

![image](https://user-images.githubusercontent.com/2697311/49812264-51298580-fd65-11e8-8127-64f956824448.png)

As you can see on the line above, the property `string` works, fine, as do all the other properties. All methods, like `custom`, `oneOf` and `arrayOf` are reported as being not accessible.

Everything seems to be working fine when transpiled to JavaScript.

The project was created using vue-cli 3.0 and I'm using the default `tsconfig.json`. I've yet to experience this error in other libraries, so I was wondering if this is somehow caused by vue-type's `d.ts` files.

**Comment by dwightjack** [comment]
Hi, I indeed think it's an issue with the typescript definition file. Sorry for the issue.

Will look into it as soon as I can. In the meanwhile you could try to update to the latest beta version of the library:

```
yarn add vue-types@beta
```

Fixes there are related to https://github.com/dwightjack/vue-types/issues/36 but I refactored the code a little bit so maybe it would work better.

**Comment by joakimbugge** [comment]
I've updated to beta (1.3.4-beta.0) and the problem seems to persist. It's not a big issue for me, the package is still working as intended run time. I'll let you know if this is still an issue after #36 gets fixed.

Thanks for responding so fast!

**Comment by dwightjack** [comment]
Looks like some sort of name collision... I'm not that expert about TS definition files but I think I've managed to make it work correctly on WebStorm (see commit here https://github.com/dwightjack/vue-types/commit/c33fe1db1a5833c358d38c2cc960da6741389140)

Published a new beta version 1.3.4-beta.1

Let me know if it works

**Comment by joakimbugge** [comment]
Works in `1.3.4-beta.1`! :)

**Comment by dwightjack** [comment]
I just published the fix as stable version `1.3.4`.

Closing for now. Feel free to open an issue if you find any other problem. :)
