### ISSUE TITLE
Cannot read property isLoose of undefined when using loose shape

### ISSUE THREAD

**Issue by EyMaddis** [dwightjack/vue-types#5]
First of, great library!

The problem ist, that `.shape().loose` is not applicable with the latest version of vue.
in this line `this` is undefined: https://github.com/dwightjack/vue-types/blob/master/src/index.js#L215

Here is the property validation of Vue: 
https://github.com/vuejs/vue/blob/01151ce3fa3cb346443d086332ec053c389ee619/src/core/util/props.js#L123

The `this` context is lost, because the validator function gets called as `validator()`, not `prop.validator`.

I am not sure how to fix this using the `isLoose` flag. A possible workaround is to use `isLoose` as a second parameter or by introducing `looseShape({})`.

**Comment by dwightjack** [comment]
Hi,

thanks for the issue. I should have fixed it. Try updating to 0.6.1.

Relevant fix is [here](https://github.com/dwightjack/vue-types/blob/master/src/utils.js#L117). I bind each validator function to the object itself. In my tests it seems to work.

**Comment by EyMaddis** [comment]
Wow, that was super quick!
No, since you did not rebuild the whole package apparently, see
https://github.com/dwightjack/vue-types/blob/master/es/utils.js#L120-L124

**Comment by dwightjack** [comment]
You're right!

Built and published as 0.6.2.

Thanks for the hint!
