### ISSUE TITLE
oneOf and default

### ISSUE THREAD

**Issue by mmintel** [dwightjack/vue-types#50]
Hi there,

I have
```
export default {
  props: {
    type: VueTypes.oneOf(["default", "primary"]).def("default")
  }
}
```

and I am calling my component without `type` prop. As I understand the code above it should set `"default"` as my `type` prop. But in browser console it's complaining about `Invalid prop: custom validator check failed for prop "type".`.

Is there some misunderstanding on my side or is it a bug?

Cheers
Marc

**Comment by dwightjack** [comment]
Hi, I've created a demo sandbox here (https://codesandbox.io/s/38828pyoxq?fontsize=14) and it seems working fine. Could you provide an implementation example?

**Comment by dwightjack** [comment]
@mmintel Since I didn't get feedback on this issue, I'm closing it just for housekeeping.

Feel free to reopen it anytime

**Comment by mmintel** [comment]
Hi there, sorry, didn't have time to investigate.

Somehow I can't replicate my original issue anymore and yeah your sandbox example proves it's working. Thanks for that. Also I used default values together with shape, but I guess it's just not possible to assign defaults to object properties. Instead I assign defaults to whole object.. or in the case of objects nested in arrays I am now just using fallbacks in my template.

Anyway thanks for investigating!

**Comment by dwightjack** [comment]
Hi,

no problem! I am glad it's working.

Yes, currently there's no way to assign default values to shape properties. I am not even sure it's doable because the object is managed directly by Vue.
