### ISSUE TITLE
Is the UMD version using the shim version when minified?

### ISSUE THREAD

**Issue by atilacamurca** [dwightjack/vue-types#57]
The minified UMD version found at <https://unpkg.com/browse/vue-types@1.5.7/umd/vue-types.min.js> is 7.87 kB. Looking at the rollup config, there's no reference to the shim version. Is the UMD version using the shim version when minified?

**Comment by dwightjack** [comment]
Hi,

nope, it's just the minified library. I'm not sure what's the expected use case here. Usually UMD versions expose the unminified and minified version of the library. Also the minified version is the one used as default file for unpkg.

What's your use case and expected behavior?

**Comment by atilacamurca** [comment]
I'm just curious to know if we can have a shim version of the UMD when minified, that is, a version that could be even lighter.

**Comment by dwightjack** [comment]
Ok. One option could be to add a bundle like `vue-types.shim.min.js`.

What do you think?

**Comment by atilacamurca** [comment]
Yeah, that's exactly it. Sorry, English it's not my primary language :smile:.

This could boost even further the UMD version, for those who uses a CDN, for instance.

**Comment by dwightjack** [comment]
Don't worry, it is not mine either 😄 .

I just wanted to get it clear. I will add the feature on the next patch version.

**Comment by dwightjack** [comment]
@atilacamurca I've added the shim in the UMD build and published the changes as v1.6.0:

https://unpkg.com/browse/vue-types@1.6.0/umd/vue-types.shim.min.js

As a side effect, the link to the pre-configured CodeSandobox has been published on the npm docs as well 🎉 .

I'm closing this for now. Feel free to re-open it if you spot any issue.

**Comment by atilacamurca** [comment]
This is really great! Thank you for your work.

I think it would be greater if we show how to use the shim version on the README. I will send a PR later for that.

Thanks again.
