### ISSUE TITLE
shape.loose does not work

### ISSUE THREAD

**Issue by EyMaddis** [dwightjack/vue-types#6]
Hi again,
I noticed that `shape({}).loose` does not work. I did some digging and noticed that the [unit test](https://github.com/dwightjack/vue-types/blob/master/test/index.spec.js#L466-L470) is actually incorrect.

I adapted the test to be breaking:
```js
   it('should validate an object with keys NOT present in the shape on `loose` mode', () => {

      const customType = VueTypes.shape(shape).loose
      expect(customType.validator({
        id: 10,
        name: 'John',
        newProperty: true
      })).toBe(true)
    })
```

Test result:

```
WARN: '[VueTypes warn]: object is missing "newProperty" property'
[...]
SUMMARY:
✔ 76 tests completed
✖ 1 test failed

FAILED TESTS:
  VuePropTypes
    `.shape`
      ✖ should validate an object with keys NOT present in the shape on `loose` mode
        PhantomJS 2.1.1 (Mac OS X 0.0.0)
      Expected false to be true
      assert@test/index.spec.js:734:27
      toBe@test/index.spec.js:2615:28
      test/index.spec.js:5672:15
```

The problem is that you use `objectAssign({ isLoose: true }, this)` (see [here](https://github.com/dwightjack/vue-types/blob/master/src/index.js#L227)).
You create a new object, instead of appending data to `this`, you create a new object. This object is however not the one which is bound to the `.shape()` function.
If `loose` would set `this.isLoose=true`, it is fixed, but I think the new object is actually intended behavior (that's why this is not a PR).

Actually the fix from https://github.com/dwightjack/vue-types/issues/5 is the problem, because this binds the context of the validator function.

**Comment by dwightjack** [comment]
Hi,

you're right. Looks like I messed it up.

In the end the only solution seems to set `isLoose` without creating a new object.
Since that validator function it's the only place where I refer to `this`, I've reverted the previous change by binding the context just on the `shape().loose` modifier.

About creating a new object: I wanted to be as spec compliant as possible to the Vue types definition, without introducing new properties, removing any `def`, `isRequired` etc getter.
Maybe that's too much thinking since the are not enumerable and won't harm...

**Comment by dwightjack** [comment]
By the way. I missed the important part: pushed a new version, let me know if it fixes the problem... sorry for the mess!

**Comment by EyMaddis** [comment]
@dwightjack It of course makes `.loose` work, but reopens #5 when `not` using `.loose`. Your tests are actually not correct on a bigger scale.
I opened PR #7 to fix this once and for all :)

**Comment by dwightjack** [comment]
Merged.

Thanks for contributing. :-)

**Comment by EyMaddis** [comment]
closed through #7

**Comment by EyMaddis** [comment]
@dwightjack don't forget https://github.com/dwightjack/vue-types/releases ;)

**Comment by dwightjack** [comment]
Yep sure.

I was thinking about a edge case. If i call something like that:

```
shape({ ... }).loose.isRequired
```

The isRequired flag will remove isLoose flags (since they are not enumerable). The solution could be here to ovewrite the `validator` function in the `.loose` flag. This way we'll get rid of the `this` issue. See https://github.com/dwightjack/vue-types/blob/feature/loose/src/index.js#L223

On the other hand I'm wondering if getting rid of the `objectAssign` thing will be a better option for cleaner and more predictable code...

**Comment by EyMaddis** [comment]
> The isRequired flag will remove isLoose flags (since they are not enumerable).

So you mean if there would be multiple flags, like `.loose.isRequired.somethingElse`?

By the way, another issue is that the order is important.
I will add a breaking test as a PR.

**Comment by dwightjack** [comment]
That's the main issue. On `.isRequired` and `.def` I'm duplicating the object with just the enumerable properties. Setting `_VueTypes_isLoose` as enumerable should fix it.

Overwriting the validator function will keep the object clean but the code itself smells...

**Comment by EyMaddis** [comment]
Why do you duplicate it at all? 
I added the `enumerable: false`, just so that Vue cannot see it.


By the way, you maybe could avoid the copying altogether if you prototype-link all the flags. I will write this down in more detail later, as I have to go now.

**Comment by dwightjack** [comment]
I just reviewed the whole thing.

`.isRequired`, `.def()` and `.loose` are all `enumerable: false` properties. Under the hood they call `Object.assign`, duplicate the source object and reassign not-enumerable modifiers (which are not copied by `Object.assign`). 

The rationale behind this was that in a previous version of the library every type was a direct reference to an object. If a flag would alter a given type it'd change it everywhere. Right now I switched to a getter which returns everytime a new object.

From that point of view duplicating is no more a necessity. The only edge case would be a "base type" which gets then used throughout the app:

```
//without duplicating
const type = VueTypes.integer.def(5);
const typeReq = type.isRequired;

//type.default === typeReq.default
```

Not sure that's a common pattern though.

**Comment by dwightjack** [comment]
Btw, I'm really appreciating the time you're spending helping on the library. Right now I'm not working on vue.js projects so feedback like yours are very welcome!

**Comment by EyMaddis** [comment]
you're welcome :)

I thought about my prototype chain idea and noticed that it will probably not work.

> The rationale behind this was that in a previous version of the library every type was a direct reference to an object. If a flag would alter a given type it'd change it everywhere. 

You can solve this by letting every base type rule return `new PropValidator()`.

```

function PropValidator(name, baseType) { // compatible with Vues requirements
  'use strict' // just in case it was called without new, should be checked
  this.type = baseType
  this.name = name
  return this
}


const VuePropTypes = { // defines all root types

  get any() {
    return new PropValidator('any', null)
  },
...
}
```

Following that, each validation rule is required to begin with `VueType.<requiredType>`, but after that, all the additional filter/flags could freely manipulate `this`.
Filters or flags would be added to `PropValidator` via `defineProperty()`.

**Comment by dwightjack** [comment]
Hi,

yes I'd keep the `toType` approach and enhance a source object with not enumerable custom properties and methods via `defineProperty`.
Right now Vue doesn't check for a plain object in `props`, but to me it looks more clean.

Anyway removing the object cloning is the best option to prevent edge cases. 
I like the addition of a `name` or maybe `_vueType_name` property. It could be useful for error reporting.

I'll open a new issue about that.
