### ISSUE TITLE
Wrong inferred type of prop when using oneOf method

### ISSUE THREAD

**Issue by IgorSzymanski** [dwightjack/vue-types#62]
https://github.com/dwightjack/vue-types/blob/b1235764c25e5174196a46edb811a56b41978c42/types/vue-types.d.ts#L95

I believe that line should look like this:
```ts
oneOf<T = any>(arr: T[]): VueTypeDef<T, T>
```

Currently, if I do something like this:
```ts
props: {
		id: VueTypes.oneOf([0, 1]).isRequired,
	},
```
Typescript assumes that prop `id` is of type `number[]`, but it should be `number` instead.

Tested it locally, and after the change, it works as - I assume - intended.

**Comment by dwightjack** [comment]
Good catch. Thank you!

Fixed in `v1.6.2`.

Since I'm not 100% confident in TypeScript feel free to open another issue or submit a PR for bugfix and improvements in the type definitions.

**Comment by IgorSzymanski** [comment]
> submit a PR for bugfix and improvements in the type definitions
I might actually do that, because I've noticed more issues with types after closer inspection.

**Comment by dwightjack** [comment]
@IgorSzymanski that would be great.

Sorry for causing issues :cry:
