### ISSUE TITLE
VueTypes.instanceOf don't support abstract class

### ISSUE THREAD

**Issue by danranVm** [dwightjack/vue-types#75]
```ts
export abstract class AbstractControl {}

VueTypes.instanceOf(AbstractControl)
```

I get an error: 

`Argument of type 'typeof AbstractControl' is not assignable to parameter of type 'Constructor'. Cannot assign an abstract constructor type to a non-abstract constructor type.`

**Comment by danranVm** [comment]
```ts
export abstract class AbstractControl {}

export abstract class FormGroup extends AbstractControl {}
export abstract class FormArray extends AbstractControl {}
export abstract class FormControl extends AbstractControl {}

export const FormControlPropType = 
  VueTypes.oneOfType([
    VueTypes.string,
    VueTypes.oneOfType([
      VueTypes.instanceOf(FormGroup),
      VueTypes.instanceOf(FormArray),
      VueTypes.instanceOf(FormControl),
    ]),
  ]) as VueTypeDef<string | AbstractControl>
```

it is work, is there a better way?

**Comment by dwightjack** [comment]
Hi,

I am not familiar with abstract classes, but I think they don't have an actual translation in JavaScript and, if so, they cannot be instantiated with the `new` construct.

My guess is that it might work using the object validator with a type parameter:

```ts
import { object } from 'vue-types'

const prop = object<AbstractControl>()
```

**Comment by danranVm** [comment]
> Hi,
> 
> I am not familiar with abstract classes, but I think they don't have an actual translation in JavaScript and, if so, they cannot be instantiated with the `new` construct.
> 
> My guess is that it might work using the object validator with a type parameter:
> 
> ```ts
> import { object } from 'vue-types'
> 
> const prop = object<AbstractControl>()
> ```

tks, it correctly infers the type of parameter
